---
title: "Plotting mentions over time"
subtitle: "rtweet: Collecting Twitter Data"
output:
  rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Plotting mentions over time}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(comment = "#>", collapse = TRUE)
```

##


```{r, eval=FALSE}
firehose <- function() {
    paste(c(letters, 0:9), collapse = ",")
}

## stream tweets for 30 minutes
rt <- stream_tweets(c(-180, -90, 180, 90),
                    timeout = (60 * 20),
                    parse = FALSE,
                    file_name = "mapdemo.json")


thisplot <- function(p, cex = 1, ...) {
    x <- p[["time"]]
    y <- p[["freq"]]
    om <- par("mai")
    xlim <- range(as.double(x), na.rm = TRUE)
    ylim <- range(y, na.rm = TRUE)
    par(bg = "#e3e3e3aa", tcl = -.025,
        family = "Proxima Nova", font.main = 1,
        cex = .8, cex.main = 1.75,
        col = rgb(0, 0, 0, .4))
    plot(x, y, col = "#98AFC7", type = "p",
         xlab = "", ylab = "",
         xaxt = "n", bty = "n", yaxt = "n")
    box()
    par(mai = om/3)
    grid(8, lty = 3, lwd = .75,
         col = rgb(0,0,0,.4))
    par(mai = om)

    rect(par()$usr[1], par()$usr[3],
         par()$usr[2], par()$usr[4],
         lwd = .75, lty = 3,
         border = rgb(0,0,0,.4))

    x1 <- x[p$filter == "English"]
    y1 <- y[p$filter == "English"]
    points(as.double(x1), y1,
           pch = 21, cex = cex,
           bg = "#3777AD66",
           col = "#3B5469")

    x2 <- x[p$filter == "Portugese"]
    y2 <- y[p$filter == "Portugese"]
    points(as.double(x2), y2,
           pch = 21, cex = cex,
           bg = "#FFB14566",
           col = "#D9A155")

    x3 <- x[p$filter == "Spanish"]
    y3 <- y[p$filter == "Spanish"]
    points(as.double(x3), y3,
           pch = 21, cex = cex,
           bg = "#623FB666",
           col = "#4E4070")

    x4 <- x[p$filter == "Japanese"]
    y4 <- y[p$filter == "Japanese"]
    points(as.double(x4), y4,
           pch = 21, cex = cex,
           bg = "#48D53966",
           col = "#4C8646")

    x5 <- x[p$filter == "und"]
    y5 <- y[p$filter == "und"]
    points(as.double(x5), y5,
           pch = 21, cex = cex,
           bg = "#B9497866",
           col = "#70002F")

    x6 <- x[p$filter == "Indonesian"]
    y6 <- y[p$filter == "Indonesian"]
    points(as.double(x6), y6,
           pch = 21, cex = cex,
           bg = "#3A936F66",
           col = "#005A36")

    x7 <- x[p$filter == "Thai"]
    y7 <- y[p$filter == "Thai"]
    points(as.double(x7), y7,
           pch = 21, cex = cex,
           bg = "#C5ADA166",
           col = "#6D5548")
}



png("twitlang.png", 7, 5.5, "in", res = 127.5)
par(family = "Proxima Nova")
p <- d %>% ts_plot("5 secs", txt = "lang",
        filter = c('en', 'pt', 'es', 'und', 'ja',
                   'in', 'tl', 'th', 'ar', 'fr', 'ru'),
                  ## 'it', 'ht', 'et', 'tr'),
        key = c('English', 'Portugese', 'Spanish',
                'und', 'Japanese', 'Indonesian', 'Filipino',
                'Thai', 'Arabic', 'French', 'Russian'),
               ## 'Italian', 'Haitian', 'Estonian', 'Turkish'),
        main = "Languages of Twitter", cex.main = 1.5,
        lwd = 1.25)
dev.off()
```
