---
title: "stream_tweets"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, eval = FALSE)
```

## stream_tweets

```{r}
## Install newest version of rtweet from Github
install.packages("devtools")
devtools::install_github("mkearney/rtweet")

## Load rtweet
library(rtweet)
```

```{r}
## Stream filter keywords
q <- paste0("hillaryclinton,imwithher,clinton,", 
	"realdonaldtrump,maga,trump,"
	"electionday")

## Stream time in seconds (x * 60 = x mins, x * 60 * 60 = x hours)
## Stream for 30 minutes
streamtime <- 30 * 60

## Filename to save json data (backup)
filename <- "rtelect.json"

## Stream election tweets
rt <- stream_tweets(q = q, timeout = streamtime, 
	file_name = filename)

## Parse json file method
#rt <- stream_tweets(q = q, timeout = streamtime, 
#	parse = FALSE, file_name = filename)
#rt <- parse_stream("rtweet_elxn.json")

## Preview tweets data
head(rt)

## Preview users data
head(users_data(rt))
```

```{r, eval=TRUE, echo=FALSE}
rt <- readRDS("/Users/mwk/r/rtelectstream.rds")
```

```{r, eval=TRUE}
## Plot time series of all tweets
ts_plot(rt, "secs")
```


```{r, eval=TRUE}
## Return ggplot2 object (must have ggplot2 installed)
p <- ts_plot(rt, by = "secs", span = .15,
	filters = c("clinton|imwithher", "trump|maga", 
		"clinton|withher|trump|maga|electionday"))

## Pretty plot
p + ggplot2::theme_minimal() + ylim(0, 2500) +
	ggplot2::labs(title = "Election Day Tweets") +
	ggplot2::scale_colour_manual("Tweets", 
		labels = c(
			"clinton|withher|trump|maga|electionday" = "All",
			"clinton|imwithher" = "Clinton", 
			"trump|maga" = "Trump"), 
		values = c("#3366ffcc", "#33ff33cc", "#dd3333cc")) + 
	ggplot2::theme(text = element_text(size = 16),
		title = element_text(size = 32)) +
	ggplot2::ggsave("rtelect.png", 5, 5)
```

