---
title: "Collecting Twitter Data"
output:
  rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Collecting Twitter Data}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include=FALSE}
knitr::opts_chunk$set(
  echo = TRUE, eval = TRUE, comment = "#>", collapse = TRUE)
```

This vignette provides a quick tour of the R package.

```{r}
library("rtweet")
```


## Authenticate

First you should set up your own credentials:

```{r, eval=FALSE}
auth_setup_default()
```

Which will look up your account on your browser.
Next we need to authenticate with it:

```{r, eval=FALSE}
auth_as("default")
```

Then we are ready to use the package with your own authentication.
If you want to set up a bot or collect a lot of information, please read the `vignette("auth", "rtweet")`.

```{r include=FALSE}
auth_as(rtweet:::rtweet_test())
```

```{r child, echo=FALSE, results='asis'}
file <- system.file("child.Rmd", package = "rtweet", mustWork = TRUE)
res <- knitr::knit_child(file, options = list(eval = TRUE), quiet = TRUE)
cat(res, sep = '\n')
```
