# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

unroll_connections <- function(from, to) {
    .Call(`_rtweet_unroll_connections`, from, to)
}

unroll_users <- function(x) {
    .Call(`_rtweet_unroll_users`, x)
}

