#' plot tweets
#'
#' @description Plot tweets class data
#'
#' @param x tweets data frame object
#' @param ggplot Logical indicating whether to plot using \pkg{ggplot2}
#' @param \dots Other arguments passed to plot
#' @importFrom grDevices hcl
#' @importFrom graphics par plot
#' @export
plot.rtweet_df <- function(x, ggplot = TRUE, ...) {
  x$group <- sample(c("a", "b", "c", "d", "e"), nrow(x), replace = TRUE)
  x$followers_count <- log(x$followers_count + 2)
  x$friends_count <- log(x$friends_count + 2)

  cols <- paste(gg_cols(5), "99", sep = "")
  par(family = "serif", xaxt = "n", yaxt = "n",
    font = 2L, col.main = "#555555",
    col.lab = "#555555", cex.main = 2,
    cex.lab = 1.25, font.lab = 2L)
  plot(x$friends_count, x$followers_count,
    pch = 16, xlab = "# of Friends", ylab = "# of Followers",
    main = "rtweet: Collecting Twitter Data",
    col = sample(cols, nrow(x), replace = TRUE),
    bty = "n", cex = 2.5)
}

#' gg_cols
#'
#' @description Generates colors like those generated by
#'  '\pkg{ggplot2}.
#' @param n Number of colors (HEX values) to return.
#' @return Character vector of HEX color codes.
#'
#' @examples
#'
#' gg_cols(8)
#' @export
gg_cols <- function(n) {
  hues = seq(15, 375, length = n + 1)
  hcl(h = hues, l = 65, c = 100)[1:n]
}


#' rtweet_df
#'
#' @description Class containing rtweet [data frame] object converted
#'  from \code{\link{tweets}} class.
#'
#' @keywords classes
#' @examples
#'
#' showClass("rtweet_df")
#' methods(class = "rtweet_df")
#' @export
rtweet_df <- setClass("rtweet_df", contains = "data.frame")



#' rt_data
#'
#' @description Convert tweets list to rtweet_df
#'
#' @param object Tweets class list object
#' @keywords classes
#' @examples
#' \dontrun{
#' tw <- search_tweets("twitter")
#' tw <- rt_data(tw)
#' tw
#' }
#' @export
rt_data <- function(object) {
	cols <- slotNames(object)
	data <- lapply(cols, function(x) slot(object, x))
	names(data) <- cols
	data <- data_frame_(data)
	new("rtweet_df", data)
}


#' Class-tweets
#'
#' @description Tweets data list class
#'
#' @keywords classes
#' @export
tweets <- setClass("tweets", slots = c(
	created_at = "POSIXct",
	status_id = "character",
	user_id = "character",
	screen_name = "character",
	followers_count = "numeric",
	friends_count = "numeric",
	statuses_count = "numeric",
	location = "character",
	verified = "logical",
	text = "character",
	retweet_count = "numeric",
	favorite_count = "numeric",
	in_reply_to_status_id = "character",
	in_reply_to_user_id = "character",
	#in_reply_to_screen_name = "character",
	is_quote_status = "logical",
	quoted_status_id = "character",
	source = "character",
	lang = "character",
	user_mentions = "character",
	hashtags = "character",
	urls = "character",
	is_retweet = "logical",
	retweet_status_id = "character",
	place_name = "character",
	country = "character",
	long1 = "numeric",
	long2 = "numeric",
	long3 = "numeric",
	long4 = "numeric",
	lat1 = "numeric",
	lat2 = "numeric",
	lat3 = "numeric",
	lat4 = "numeric"))


#' make_tweets
#'
#' @description Convert API data to S4 Class list object
#'
#' @name make_tweets
#' @param x Tweets data frame
#' @keywords classes
#' @import methods
#' @export
make_tweets <- function(x) {
  ux <- users_data(x)
  ux <- ux[, !names(ux) %in% c("lang", "screen_name", "created_at")]
  x <- merge(x, ux, by = "user_id", all = TRUE)

  urls <- sapply(x$urls, paste, collapse = " ")
  user_mentions <- sapply(x$user_mentions, paste, collapse = " ")
  hashtags <- sapply(x$hashtags, paste, collapse = " ")

  new("tweets",
	created_at = as.POSIXct(x$created_at),
	status_id = as.character(x$status_id),
	user_id = as.character(x$user_id),
	screen_name = as.character(x$screen_name),
	followers_count = as.double(x$followers_count),
	friends_count = as.double(x$friends_count),
	statuses_count = as.double(x$statuses_count),
	location = as.character(x$location),
	verified = as.logical(x$verified),
	text = as.character(x$text),
	retweet_count = as.double(x$retweet_count),
	favorite_count = as.double(x$favorite_count),
	in_reply_to_status_id = as.character(x$in_reply_to_status_id),
	in_reply_to_user_id = as.character(x$in_reply_to_user_id),
	#in_reply_to_screen_name = as.character(x$in_reply_to_screen_name),
	is_quote_status = as.logical(x$is_quote_status),
	quoted_status_id = as.character(x$quoted_status_id),
	source = as.character(x$source),
	lang = as.character(x$lang),
	user_mentions = as.character(x$user_mentions),
	hashtags = as.character(x$hashtags),
	urls = as.character(x$urls),
	is_retweet = as.logical(x$is_retweet),
	retweet_status_id = as.character(x$retweet_status_id),
	place_name = as.character(x$place_name),
	country = as.character(x$country),
	long1 = as.numeric(x$long1),
	long2 = as.numeric(x$long2),
	long3 = as.numeric(x$long3),
	long4 = as.numeric(x$long4),
	lat1 = as.numeric(x$lat1),
	lat2 = as.numeric(x$lat2),
	lat3 = as.numeric(x$lat3),
	lat4 = as.numeric(x$lat4))
}



#' Method show
#'
#' @description Show method for class \code{rtweet_df}
#' @param object tweets object
#'
#' @exportMethod show
setMethod("show", "rtweet_df", function(object) print.tweets(object))

trunc_text <- function(txt, n) {
  paste0(strtrim(encodeString(txt), width = n), " ...")
}

#' print tweets
#'
#' @description print tweets class object
#' @param x Object of class \code{tweets}.
#' @param \dots Other arguments passed to \code{print}.
#' @export
print.tweets <- function(x, ...) {
  mp <- getOption("max.print")
  options(max.print = 200)

  cat("rtweet", fill = TRUE)
  cat("tweet data:",
    paste0(nrow(x), " tweets (rows) x ",
      ncol(x), " variables (columns)"),
    fill = TRUE)
  cat("\n")

  x$created_at <- trunc_text(x$created_at, 10)
  x$text <- trunc_text(x$text, 16)
  x$location <- trunc_text(x$location, 10)
  x$urls <- trunc_text(x$urls, 10)
  x$hashtags <- trunc_text(x$hashtags, 10)
  x$user_mentions <- trunc_text(x$user_mentions, 10)
  x$place_name <- trunc_text(x$place_name, 10)
  x$source <- trunc_text(x$source, 10)

  print(x, na.print = "NA")

  options(max.print = mp)
}
