#' plot tweets
#'
#' @description Plot tweets class data
#'
#' @param x tweets object
#' @param \dots Other arguments passed to plot
#' @importFrom grDevices hcl
#' @importFrom graphics par plot
#' @export
plot.tweets <- function(x, ...) {
  x <- rt_data(x)
  x$group <- sample(c("a", "b", "c", "d", "e"),
    nrow(x), replace = TRUE)

  if ("followers_count" %in% names(x)) {
    x$xvar <- log(x$friends_count + 2)
    x$yvar <- log(x$followers_count + 2)
    xvar <- "# of Friends"
    ylab <- "# of Followers"
  } else {
    x$xvar <- log(x$favorite_count + 2)
    x$yvar <- log(x$retweet_count + 2)
    xlab <- "# of Favorites"
    ylab <- "# of Retweets"
  }

  cols <- paste(gg_cols(5), "99", sep = "")
  par(family = "serif", xaxt = "n", yaxt = "n",
    font = 2L, col.main = "#333333",
    col.lab = "#333333", cex.main = 2,
    cex.lab = 1.25, font.lab = 2L)
  plot(x$xvar, x$yvar,
    pch = 16, xlab = xlab, ylab = ylab,
    main = "rtweet: Collecting Twitter Data",
    col = sample(cols, nrow(x), replace = TRUE),
    bty = "n", cex = 2.5)
}

#' plot users
#'
#' @description Plot users class data
#'
#' @param x users object
#' @param \dots Other arguments passed to plot
#' @importFrom grDevices hcl
#' @importFrom graphics par plot
#' @export
plot.users <- function(x, ...) {
  x <- rt_data(x)
  x$group <- sample(c("a", "b", "c", "d", "e"),
    nrow(x), replace = TRUE)

  if ("followers_count" %in% names(x)) {
    x$xvar <- log(x$friends_count + 2)
    x$yvar <- log(x$followers_count + 2)
    xlab <- "# of Friends"
    ylab <- "# of Followers"
  } else {
    x$xvar <- log(x$favorite_count + 2)
    x$yvar <- log(x$retweet_count + 2)
    xlab <- "# of Favorites"
    ylab <- "# of Retweets"
  }

  cols <- paste(gg_cols(5), "99", sep = "")
  par(family = "serif", xaxt = "n", yaxt = "n",
    font = 2L, col.main = "#333333",
    col.lab = "#333333", cex.main = 2,
    cex.lab = 1.25, font.lab = 2L)
  plot(x$xvar, x$yvar,
    pch = 16, xlab = xlab, ylab = ylab,
    main = "rtweet: Collecting Twitter Data",
    col = sample(cols, nrow(x), replace = TRUE),
    bty = "n", cex = 2.5)
}

na_omit <- function(x) {
	isna <- unlist(lapply(x, function(.) is.na(.)),
		recursive = FALSE)
	x[!isna]
}


#' gg_cols
#'
#' @description Generates colors like those generated by
#'  '\pkg{ggplot2}.
#' @param n Number of colors (HEX values) to return.
#' @return Character vector of HEX color codes.
#'
#' @examples
#'
#' gg_cols(8)
#' @keywords internal
#' @export
gg_cols <- function(n) {
  hues = seq(15, 375, length = n + 1)
  hcl(h = hues, l = 65, c = 100)[1:n]
}


#' rt_data
#'
#' @description Convert tweets and users objects
#'   to data frames
#'
#' @param object Tweets class list object
#' @keywords classes
#' @examples
#' \dontrun{
#' tw <- search_tweets("twitter")
#' tw <- rt_data(tw)
#' tw
#' }
#' @export
rt_data <- function(object) {
	cols <- slotNames(object)
	data <- lapply(cols, function(.) slot(object, .))
	names(data) <- cols
	#data <- data_frame_(data)
  data_frame_(data)
	#rtweet_table(data)
}

#' Class-users
#'
#' @description Users data list class
#'
#' @keywords classes
#' @export
users <- setClass("users",
  slots = c(
    user_id = "character",
    name = "character",
    screen_name = "character",
    location = "character",
    description = "character",
    url = "character",
    protected = "logical",
    followers_count = "integer",
    friends_count = "integer",
    listed_count = "integer",
    favourites_count = "integer",
    statuses_count = "integer",
    created_at = "POSIXct",
    utc_offset = "character",
    time_zone = "character",
    geo_enabled = "logical",
    verified = "logical",
    lang = "character",
    description_urls = "matrix"))


#' Class-tweets
#'
#' @description Tweets data list class
#'
#' @keywords classes
#' @export
tweets <- setClass("tweets",
  slots = c(
  	created_at = "POSIXct",
    user_id = "character",
    screen_name = "character",
    status_id = "character",
  	retweet_count = "integer",
  	favorite_count = "integer",
    text = "character",
  	in_reply_to_status_id = "character",
  	in_reply_to_user_id = "character",
  	in_reply_to_screen_name = "character",
  	is_quote_status = "logical",
  	quoted_status_id = "character",
  	source = "character",
  	lang = "character",
  	mentions_user_id = "matrix",
    mentions_screen_name = "matrix",
  	hashtags = "matrix",
  	urls = "matrix",
  	is_retweet = "logical",
  	retweet_status_id = "character",
  	place_name = "character",
  	country = "character",
  	coordinates = "matrix"))

#' make_tweets
#'
#' @description Convert data to S4 tweets object
#'
#' @name make_tweets
#' @param x Tweets data frame
#' @keywords classes
#' @import methods
#' @export
make_tweets <- function(x) {
  ux <- users_data(x)
  ux <- ux[, !names(ux) %in% c("lang", "screen_name", "created_at")]
  x <- merge(x, ux, by = "user_id", all = TRUE)

  new("tweets",
  	created_at = as.POSIXct(x$created_at),
    user_id = as.character(x$user_id),
    screen_name = as.character(x$screen_name),
  	status_id = as.character(x$status_id),
    retweet_count = as.integer(x$retweet_count),
    favorite_count = as.integer(x$favorite_count),
  	text = as.character(x$text),
  	in_reply_to_status_id = as.character(x$in_reply_to_status_id),
  	in_reply_to_user_id = as.character(x$in_reply_to_user_id),
  	in_reply_to_screen_name = as.character(x$in_reply_to_screen_name),
  	is_quote_status = as.logical(x$is_quote_status),
  	quoted_status_id = as.character(x$quoted_status_id),
  	source = as.character(x$source),
  	lang = as.character(x$lang),
  	mentions_user_id = as.matrix(x$mentions_user_id),
    mentions_screen_name = as.matrix(x$mentions_screen_name),
  	hashtags = as.matrix(x$hashtags),
  	urls = as.matrix(x$urls),
  	is_retweet = as.logical(x$is_retweet),
  	retweet_status_id = as.character(x$retweet_status_id),
  	place_name = as.character(x$place_name),
  	country = as.character(x$country),
  	coordinates = matrix(x$coordinates))
}

#' make_users
#'
#' @description Convert data to S4 users object
#'
#' @name make_users
#' @param x Users data frame
#' @keywords classes
#' @import methods
#' @export
make_users <- function(x) {
  new("users",
    user_id = as.character(x$user_id),
    name = as.character(x$name),
    screen_name = as.character(x$screen_name),
    location = as.character(x$location),
    description = as.character(x$description),
    url = as.character(x$url),
    protected = as.logical(x$protected),
    followers_count = as.integer(x$followers_count),
    friends_count = as.integer(x$friends_count),
    listed_count = as.integer(x$listed_count),
    favourites_count = as.integer(x$favourites_count),
    statuses_count = as.integer(x$statuses_count),
    created_at = as.POSIXct(x$created_at),
    utc_offset = as.character(x$utc_offset),
    time_zone = as.character(x$time_zone),
    geo_enabled = as.logical(x$geo_enabled),
    verified = as.logical(x$verified),
    lang = as.character(x$lang),
    description_urls = as.matrix(x$description_urls))
}

#' Method show
#'
#' @description Show method for class \code{tweets}
#' @param object tweets object
#'
#' @exportMethod show
setMethod("show", "tweets",
  function(object) print.tweets(object))

trunc_text <- function(txt, n) {
  chars <- unlist(lapply(encodeString(txt), nchar))
  dots <- rep("", length(chars))
  dots[chars > n] <- ".."
  paste0(strtrim(
    gsub('"', "", gsub("c[(]|[)]|['']", "",
      encodeString(txt))),
    width = n), dots)
}

#' Method show
#'
#' @description Show method for class \code{users}
#' @param object users object
#'
#' @exportMethod show
setMethod("show", "users",
  function(object) print.users(object))

spacer <- function(.) paste(rep(" ", .), collapse = "")

#' print users
#'
#' @description print users class object
#' @param x Object of class \code{users}.
#' @param \dots Other arguments passed to \code{print}.
#' @export
print.users <- function(x, ...) {
  print(rt_data(x), max = 100)
}

#' print tweets
#'
#' @description print tweets class object
#' @param x Object of class \code{tweets}.
#' @param \dots Other arguments passed to \code{print}.
#' @export
print.tweets <- function(x, ...) {
  cat("tweets-class [rtweet]", fill = TRUE)
  cat("\t")
  cat(paste0(length(na_omit(x@status_id)), " tweets (rows) x ",
      length(slotNames(x)), " variables (columns)"),
    fill = TRUE)
  cat("\n")
  cat("Variable Names:", fill = TRUE)

  pp1 <- paste("\t", slotNames(x)[1:12])
  max <- max(sapply(pp1, nchar))

  s <- sapply(max - sapply(pp1, nchar), spacer)

  pp2 <- c(paste("\t", slotNames(x)[13:23]), "")
  pp <- mapply(function(., s, j) paste(., s, j, "\n"),
    pp1, s, pp2)
  cat(pp)
  cat("\n")

  cat("Number of unique users =",
    length(unique(x@user_id)), fill = TRUE)
  cat("Number of retweet statuses =",
    sum(x@is_retweet, na.rm = TRUE), fill = TRUE)
  cat("Number of quote statuses =",
    sum(x@is_quote_status, na.rm = TRUE), fill = TRUE)
  cat("Average number of favorites =",
    round(mean(x@favorite_count,
      na.rm = TRUE), 0), fill = TRUE)
  cat("Average number of retweets =",
    round(mean(x@retweet_count,
      na.rm = TRUE), 0), fill = TRUE)
  cat("Total number of hashtags =",
    length(unlist(x@hashtags)), fill = TRUE)
  cat("Total number of mentions =",
    length(unlist(x@mentions_user_id)), fill = TRUE)
  cat("First tweet = ")
  print(min(x@created_at, na.rm = TRUE))
  cat("Last tweet = ")
  print(max(x@created_at, na.rm = TRUE))
  cat("\n")

  cat("Preview:", fill = TRUE)

  print(data.frame(
    date = as.Date(x@created_at),
    screen_name = x@screen_name,
    rtweets = x@retweet_count,
    favorites = x@favorite_count,
    hashtags = trunc_text(x@hashtags, 10),
    text = trunc_text(x@text, 60)),
    quote = FALSE,
    right = FALSE,
    max = 30,
    print.gap = 2L,
    na.print = NULL)
}

